services:
  app:
    build: .
    ports:
      - "8080:8081"
    networks:
      - taskmanager-network
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: fares
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - taskmanagersql:/var/lib/postgresql
    networks:
      - taskmanager-network
networks:
  taskmanager-network:
    driver: bridge

volumes:
  taskmanagersql:
